---
services:
  code:
    image: lscr.io/linuxserver/code-server:latest
    environment:
      DEFAULT_WORKSPACE: /decrypted
      DOCKER_MODS: "thekelvinliu/lsio-mod-gocryptfs:latest"
      PGID: 1000
      PUID: 1000
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - 8443:8443
    volumes:
      - ./encrypted-company-secrets:/encrypted/company-secrets
      - ./encrypted-personal-documents:/encrypted/personal-documents
      - ./gocryptfs:/gocryptfs
